### ISSUE TITLE
ImportError: cannot import name 'PoissonHMM'

### ISSUE THREAD

**Issue by drsax93** [nelpy/nelpy#259]
Hello,
I've just set up nelpy - I'm working on mac OSX.  I'm getting `ImportError: cannot import name 'PoissonHMM'` as I try to import `nelpy.analysis`, after importing `nelpy as nel`.
I have hmm learn installed and up to date as well, but I can't locate the class PoissonHMM in the hmm.py file.
Any advice?

Thanks,
Giuseppe

**Comment by ckemere** [comment]
Did you use @eackermann's fork: https://github.com/eackermann/hmmlearn ?

**Comment by eackermann** [comment]
In case it helps: if you have the official hmmlearn installed, you can put the modified fork that nelpy uses in the same directory as your analysis code, so that the local version takes precedence above the installed version, but only when you're working in that particular directory.

But also, there is no reason that the fork should remain separate from the main hmmlearn repo, since it only adds a PoissonHmm class, and fixed some log likelihood calculations that have since been fixed in the main repo as well, so I really should just create a pull request so that nelpy will work with the official hmmlearn. I'll prioritize this and try to get it landed soon.

**Comment by drsax93** [comment]
Thanks for the help!
I managed to sort it out, it was a bit confusing but now everything makes sense.

Cheers,
Giuseppe

Il giorno 14 ago 2018, alle ore 19:54, Etienne Ackermann <notifications@github.com<mailto:notifications@github.com>> ha scritto:


In case it helps: if you have the official hmmlearn installed, you can put the modified fork that nelpy uses in the same directory as your analysis code, so that the local version takes precedence above the installed version, but only when you're working in that particular directory.

But also, there is no reason that the fork should remain separate from the main hmmlearn repo, since it only adds a PoissonHmm class, and fixed some log likelihood calculations that have since been fixed in the main repo as well, so I really should just create a pull request so that nelpy will work with the official hmmlearn. I'll prioritize this and try to get it landed soon.
