### ISSUE TITLE
Slow epoch array complement

### ISSUE THREAD

**Issue by ckemere** [nelpy/nelpy#260]
I discovered that for a medium/large-ish epoch array of ~10K short epochs in a larger session, finding the complement is quite slow. This might be worth optimizing.

**Comment by eackermann** [comment]
After some profiling, all the code seems very fast except for the last line, `return complement[domain]` which restricts the complement to the underlying domain (also an EpochArray).

So the root cause of the slow performance is the `intersect(epocharray)` call. However, in 99% of cases, the domain is either (-inf, inf) or some single finite interval [a, b), and for both of those cases we do not need to call the intersection.

So with a simple check we can speed up the complementation significantly (this is now live in the develop branch), but the intersection method has not been optimized yet.

**Comment by eackermann** [comment]
For reference, this quickfix sped up complementation of a 50k epoch array from approx 30 seconds to 3 ms.
