### ISSUE TITLE
Implement downsampling for ndarray and list

### ISSUE THREAD

**Issue by jchutrue** [nelpy/nelpy#271]
Currently downsample_analogsignarray() only downsamples for AnalogSignalArrays, but we would like this function to be more general and able to handle other input data types such as an ndarray or list

**Comment by jchutrue** [comment]
I would now argue that the cost of cluttering nelpy with support for other objects outweighs the benefit of extending various functions with this kind of support. There are few reasons not to work with ASAs, especially when they are very easy to create and less susceptible to user error since the data and sampling rate are bundled together. 

If we want to support multiple objects for some of these basic operations, we should have this in a separate signal processing package. @eackermann any thoughts?

**Comment by eackermann** [comment]
I agree with you. As long as it’s easy to move into, and out of, the nelpy objects, I’d say there’s little reason to try and support all kinds of other non-nelpy objects.

And it’s certainly pretty straightforward to move into and out of an ASA.

Filtering and downsampling was somewhat of an exception, since we planned to do that BEFORE creating nelpy objects. But that’s really where jagular comes in, which was of course designed as the “separate preprocessing package” that you allude to.

So no need to add it into nelpy, but proper/safe/smart downsampling would be great to have in jagular or elsewhere.

**Comment by jchutrue** [comment]
That sounds good. I'm going to close this out and implement the signal processing tools external to nelpy.
