### ISSUE TITLE
Casting AnalogSignalArray to BinnedSpikeTrainArray fails when ASA support has overlapping epochs

### ISSUE THREAD

**Issue by jchutrue** [nelpy/nelpy#277]
Executing `nel.BinnedSpikeTrainArray(asa[replay_cand_eps])` fails with `IndexError: index 1377 is out of bounds for axis 0 with size 1373`. Data attached below

**Comment by jchutrue** [comment]
Note that this file should be unzipped through the OS first before calling `nel.load_pkl()`
[cast-problem-data.nel.zip](https://github.com/nelpy/nelpy/files/2861514/cast-problem-data.nel.zip)

**Comment by eackermann** [comment]
This is not really a bug, but it could be hard to trace down. The issue is that we support overlapping epochs, since they are sometimes useful.

If you then do `asa[eps]` where `eps` has many overlapping epochs, then `asa` will have all the samples contained in the union of the eps, as expected, but then `asa.lenghts` will be (perhaps) unexpected, since `asa.n_samples` will no longer equal `asa.lenghts.sum()`. Herein lies your problem. You cannot meaningfully cast a multi-overlapping-support-asa to a BinnedSpikeTrainArray. (What should the desired output be? It's unclear...)

So if you merged your candidates first, then there'd be no problem. I'm tempted to close this as an issue, but I'll leave it for you to close, or to suggest where you want a warning or an exception to be raised.

**Comment by jchutrue** [comment]
Either a warning or exception would be helpful. Otherwise, that all makes sense, and this issue should be closed.

**Comment by jchutrue** [comment]
Addressed in #278
